# Secrets for TIFA - Local Development
# For production deployment, add your real API keys

GEMINI_API_KEY_1 = "AIzaSyCfCmnykXNOo9ddQuxs0afAcYAk8giMjKc"
GEMINI_API_KEY_2 = "AIzaSyDyp1K0uEX7AWkhb0_6Ugc0MLm8Wlwe2ss"

# Optional additional keys for load balancing
GEMINI_API_KEY_3 = ""
GEMINI_API_KEY_4 = ""